version: "3.9"

services:
  backend:
    build: .
    env_file:
      - .env   # <-- load all variables from .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
